depot/machine-images

- .github/workflows/buildkit.yml
- buildkit/buildkit.pkr.hcl
- buildkit/provision.sh
* Updates BuildKit to v0.10.4
* Pushes AMI to all default AWS regions
> Update to BuildKit 0.10.4, push to all default AWS regions

- .github/workflows/docker.yml
- docker/docker.pkr.hcl
- docker/provision.sh
Adds a new machine image that contains Docker
> Add docker machine image

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.3-depot.1
> Upgrade BuildKit to v0.11.3-depot.1

- buildkit/provision.sh
Depends on https://github.com/depot/buildkit/pull/3
> feat: update buildkitd to support stable digests

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.6.0
> Upgrade machine-agent to v1.6.0

- .github/workflows/buildkit.yml
- buildkit/provision.sh
This includes reporting disk stats such as available bytes and inodes
> Upgrade machine-agent to v1.7.0

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.8.0
> Update machine-agent to v1.8.0

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.8.1
> Update machine-agent to v1.8.1

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.4-depot.2
> Update to BuildKit v0.11.4-depot.2

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.9.0
> Update to machine-agent v1.9.0

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.5-depot.2
> feat: update to buildkit with profiling

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.10.0
> feat: update machine-agent to optionally send buildkitd profiles

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.10.1
> Update machine-agent to v1.10.1

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.5-depot.4
https://github.com/depot/buildkit/releases/tag/v0.11.5-depot.5
> feat: update buildkit with fixes for unique fileops and perf with 12 concur pushers

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.12.0
> Upgrade machine-agent to v1.12.0

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.6-depot.1
> Upgrade to BuildKit v0.11.6-depot.1

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.6-depot.3
> Update BuildKit to v0.11.6-depot.3

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.13.0
> Update machine-agent to v1.13.0

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/pull/19
> fix: release 0.11.6 with panic fixes

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/pull/36
Signed-off-by: Chris Goller <goller@gmail.com>
> feat: update machine-agent to 1.16.0

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/pull/23
> feat: update buildkit with image export refactor

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.6-depot.7
> Upgrade BuildKit to v0.11.6-depot.7

- .github/workflows/buildkit.yml
- buildkit/provision.sh
This includes upstream panic fixes as well
as our patch for SIMD SHA256 calculations.
> feat: update buildkit to v0.11.6-depot.8

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/pull/48
> feat(ceph): update machine-agent with fstrim

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.21.0
> feat: update machine-agent skipping background download

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.6-depot.10
> fix(buildkit): remove unnecessary panics in docker frontend

- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.6-depot.11
> feat: update buildkitd to disable boltdb freelist

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/releases/tag/v1.23.0
> Upgrade machine-agent to v1.23.0

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/releases/tag/v0.11.6-depot.14
> fix(buildkit): prevent stargz boltdb transaction deadlock

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/pull/36
https://github.com/depot/buildkit/pull/39
https://github.com/depot/buildkit/pull/41
https://github.com/depot/machine-agent/pull/69
https://github.com/depot/machine-agent/pull/70
https://github.com/depot/machine-agent/pull/71
> feat: release buildkit fixes and status reporting

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/buildkit/pull/44
> fix(buildkit): start single status report cxn to API

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/pull/74
https://github.com/depot/machine-agent/pull/73
https://github.com/depot/buildkit/pull/60
https://github.com/depot/buildkit/pull/59
https://github.com/depot/buildkit/pull/56
> feat: run-time concurrency for push and report layer inodes

- .github/workflows/buildkit.yml
- buildkit/provision.sh
https://github.com/depot/machine-agent/pull/75
https://github.com/depot/buildkit/pull/61
https://github.com/depot/buildkit/pull/58
> feat: return SBOMs; fix stable digests; add args
